---- DEDICATED WAREHOUSES ----

-- Create dedicated warehouses for user groups

-- Data Scientists
CREATE WAREHOUSE DS_WH 
WITH WAREHOUSE_SIZE = 'SMALL'
WAREHOUSE_TYPE = 'STANDARD' 
AUTO_SUSPEND = 300 
AUTO_RESUME = TRUE 
MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 1 
SCALING_POLICY = 'STANDARD';

-- DBA
CREATE WAREHOUSE DBA_WH 
WITH WAREHOUSE_SIZE = 'XSMALL'
WAREHOUSE_TYPE = 'STANDARD' 
AUTO_SUSPEND = 300 
AUTO_RESUME = TRUE 
MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 1 
SCALING_POLICY = 'STANDARD';

-- Create roles

CREATE ROLE DATA_SCIENTIST;
GRANT USAGE ON WAREHOUSE DS_WH TO ROLE DATA_SCIENTIST;

CREATE ROLE DBA;
GRANT USAGE ON WAREHOUSE DBA_WH TO ROLE DBA;

-- Setting up users

-- Data Scientists
CREATE USER DS1 PASSWORD = 'DS1' LOGIN_NAME = 'DS1' DEFAULT_ROLE='DATA_SCIENTIST' DEFAULT_WAREHOUSE = 'DS_WH'  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE DATA_SCIENTIST TO USER DS1;

-- DBA
CREATE USER DBA1 PASSWORD = 'DBA1' LOGIN_NAME = 'DBA1' DEFAULT_ROLE='DBA' DEFAULT_WAREHOUSE = 'DBA_WH'  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE DBA TO USER DBA1;

---- SCALE UP ----

ALTER WAREHOUSE DS_WH SET WAREHOUSE_SIZE='MEDIUM';

---- SCALE OUT (MULTI CLUSTER WAREHOUSES) ----

ALTER WAREHOUSE DS_WH SET MIN_CLUSTER_COUNT=1;
ALTER WAREHOUSE DS_WH SET MAX_CLUSTER_COUNT=3;

---- CACHING ----

-- run similar queries on same warehouse

SELECT AVG(C_BIRTH_YEAR) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER; // 6s
SELECT AVG(C_BIRTH_YEAR) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER; // 80ms

---- CLUSTERING ----
-- Cluster keys by columns frequently used in WHERE-clauses (Could have multiple cluster keys)
ALTER TABLE MY_TABLE CLUSTER BY ( DATE ) 

// Cluster key using function
ALTER TABLE MY_TABLE CLUSTER BY ( MONTH(DATE) )



