----  TIME TRAVEL: Use-case: Update data by mistake ----
UPDATE EXERCISE_DB.PUBLIC.EMPLOYEES
SET FIRST_NAME = 'Joyen' // forgot where-clause

-- Using time travel: Method 2 minutes back
SELECT * FROM EXERCISE_DB.PUBLIC.EMPLOYEES at (OFFSET => -60*2);

-- Using time travel: Method 2 - before timestamp
SELECT * FROM EXERCISE_DB.PUBLIC.EMPLOYEES before (timestamp => '2021-04-15 17:47:50.581'::timestamp);

-- Using time travel: Method 3 - before Query ID
SELECT * FROM EXERCISE_DB.PUBLIC.EMPLOYEES before (statement => '019b9ee5-0500-8473-0043-4d8300073062');

---- RESTORING DATA ----

-- Bad method (does not keep table metadata history)

CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.EMPLOYEES as
SELECT * FROM EXERCISE_DB.PUBLIC.EMPLOYEES before (statement => '019b9eea-0500-845a-0043-4d830007402a')

-- Good method (keep table metadata history)

CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.EMPLOYEES_BACKUP as
SELECT * FROM EXERCISE_DB.PUBLIC.EMPLOYEES before (statement => '019b9ef0-0500-8473-0043-4d830007309a');

TRUNCATE EXERCISE_DB.PUBLIC.EMPLOYEES;

INSERT INTO EXERCISE_DB.PUBLIC.EMPLOYEES
SELECT * FROM EXERCISE_DB.PUBLIC.EMPLOYEES_BACKUP;

---- UNDROP TABLE ----

-- UNDROP Tables
UNDROP TABLE EXERCISE_DB.PUBLIC.EMPLOYEES;

-- UNDROP Schemas
UNDROP SCHEMA EXERCISE_DB.PUBLIC;

-- UNDROP Database
UNDROP DATABASE EXERCISE_DB;

-- Restore replaced table
ALTER TABLE EXERCISE_DB.PUBLIC.EMPLOYEES
RENAME TO EXERCISE_DB.PUBLIC.EMPLOYEES_WRONG;

UNDROP table EXERCISE_DB.PUBLIC.EMPLOYEES;
