---- DATA SHARING ----
-- Create a share object
CREATE OR REPLACE SHARE CUSTOMERS_SHARE;

-- Setup grants
GRANT USAGE ON DATABASE EXERCISE_DB TO SHARE CUSTOMERS_SHARE; 
GRANT USAGE ON SCHEMA EXERCISE_DB.PUBLIC TO SHARE CUSTOMERS_SHARE; 
GRANT SELECT ON TABLE EXERCISE_DB.PUBLIC.CUSTOMERS TO SHARE CUSTOMERS_SHARE; 
// Share all tables in database: GRANT SELECT ON ALL TABLES IN DATABASE EXERCISE_DB TO SHARE CUSTOMERS_SHARE; 
// Share all tables in schema: GRANT SELECT ON ALL TABLES IN SCHEMA EXERCISE_DB.PUBLIC TO SHARE CUSTOMERS_SHARE; 

-- Validate Grants
SHOW GRANTS TO SHARE CUSTOMERS_SHARE;

-- Add consumer account
ALTER SHARE CUSTOMERS_SHARE ADD ACCOUNT=<consumer-snowflake-account-id>;

---- CONSUME SHARE ----
SHOW SHARES;
DESC SHARE <share-id>;

-- Create database with the shared content
CREATE OR REPLACE DATABASE SHARED_CONSUMERS FROM SHARE <share-id>;

---- SHARE WITH NON-SNOWFLAKE USERS ----

-- Create managed reader account --
CREATE MANAGED ACCOUNT reader_account
ADMIN_NAME = reader_admin,
ADMIN_PASSWORD = 'readerAdminPassword123',
TYPE = READER;

-- Show accounts
SHOW MANAGED ACCOUNTS;

-- Share with reader account
ALTER SHARE CUSTOMERS_SHARE ADD ACCOUNT = <reader-account-id>;

---- CONSUME SHARE AS READER  ----
-- Show all shares
SHOW SHARES;
DESC SHARE <share-id>;

-- Create a database in consumer account using the share
CREATE DATABASE DATA_SHARE_DB FROM SHARE <share-id>;

-- Setup virtual warehouse
CREATE WAREHOUSE READ_WH WITH
WAREHOUSE_SIZE='X-SMALL'
AUTO_SUSPEND = 180
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

---- CREATE READER USERS ----
-- Create user
CREATE USER READ_USER PASSWORD = 'readerUserPassword123'

-- Grant usage on warehouse
GRANT USAGE ON WAREHOUSE READ_WH TO ROLE PUBLIC;

-- Grating privileges on a Shared Database for other users
GRANT IMPORTED PRIVILEGES ON DATABASE DATA_SHARE_DB TO ROLE PUBLIC;

---- CREATE A SECURE VIEW TO SHARE ----
-- Create secure view -- 
CREATE OR REPLACE SECURE VIEW EXERCISE_DB.PUBLIC.CUSTOMER_VIEW_SECURE AS
SELECT 
    FIRST_NAME,
    LAST_NAME,
    EMAIL
FROM EXERCISE_DB.PUBLIC.CUSTOMERS
WHERE JOB != 'DATA SCIENTIST' 

-- Grant permissions
GRANT USAGE ON DATABASE EXERCISE_DB TO SHARE CUSTOMERS_SHARE;
GRANT USAGE ON SCHEMA EXERCISE_DB.PUBLIC TO SHARE CUSTOMERS_SHARE;
GRANT SELECT ON VIEW EXERCISE_DB.PUBLIC.CUSTOMER_VIEW_SECURE TO SHARE CUSTOMERS_SHARE;
